// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/jefrryss/go-grpc-microservices/InventoryService/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function with given fields: ctx, id
func (_m *Service) GetPart(ctx context.Context, id uuid.UUID) (*model.Part, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Part, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Part); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type Service_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Service_Expecter) GetPart(ctx interface{}, id interface{}) *Service_GetPart_Call {
	return &Service_GetPart_Call{Call: _e.mock.On("GetPart", ctx, id)}
}

func (_c *Service_GetPart_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Service_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Service_GetPart_Call) Return(_a0 *model.Part, _a1 error) *Service_GetPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetPart_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Part, error)) *Service_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function with given fields: ctx, filters
func (_m *Service) ListParts(ctx context.Context, filters *model.Filter) ([]*model.Part, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []*model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filter) ([]*model.Part, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Filter) []*model.Part); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Filter) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type Service_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - filters *model.Filter
func (_e *Service_Expecter) ListParts(ctx interface{}, filters interface{}) *Service_ListParts_Call {
	return &Service_ListParts_Call{Call: _e.mock.On("ListParts", ctx, filters)}
}

func (_c *Service_ListParts_Call) Run(run func(ctx context.Context, filters *model.Filter)) *Service_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Filter))
	})
	return _c
}

func (_c *Service_ListParts_Call) Return(_a0 []*model.Part, _a1 error) *Service_ListParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_ListParts_Call) RunAndReturn(run func(context.Context, *model.Filter) ([]*model.Part, error)) *Service_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
