// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	payment_v1 "github.com/jefrryss/go-grpc-microservices/shared/pkg/proto/payment/v1"
	mock "github.com/stretchr/testify/mock"
)

// PaymentServiceServer is an autogenerated mock type for the PaymentServiceServer type
type PaymentServiceServer struct {
	mock.Mock
}

// PayOrder provides a mock function with given fields: _a0, _a1
func (_m *PaymentServiceServer) PayOrder(_a0 context.Context, _a1 *payment_v1.PayOrderRequest) (*payment_v1.PayOrderResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *payment_v1.PayOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment_v1.PayOrderRequest) (*payment_v1.PayOrderResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *payment_v1.PayOrderRequest) *payment_v1.PayOrderResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment_v1.PayOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *payment_v1.PayOrderRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedPaymentServiceServer provides a mock function with no fields
func (_m *PaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {
	_m.Called()
}

// NewPaymentServiceServer creates a new instance of PaymentServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentServiceServer {
	mock := &PaymentServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
