// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	payment_v1 "github.com/jefrryss/go-grpc-microservices/shared/pkg/proto/payment/v1"
)

// PaymentServiceClient is an autogenerated mock type for the PaymentServiceClient type
type PaymentServiceClient struct {
	mock.Mock
}

// PayOrder provides a mock function with given fields: ctx, in, opts
func (_m *PaymentServiceClient) PayOrder(ctx context.Context, in *payment_v1.PayOrderRequest, opts ...grpc.CallOption) (*payment_v1.PayOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *payment_v1.PayOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *payment_v1.PayOrderRequest, ...grpc.CallOption) (*payment_v1.PayOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *payment_v1.PayOrderRequest, ...grpc.CallOption) *payment_v1.PayOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment_v1.PayOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *payment_v1.PayOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentServiceClient creates a new instance of PaymentServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentServiceClient {
	mock := &PaymentServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
