// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafePaymentServiceServer is an autogenerated mock type for the UnsafePaymentServiceServer type
type UnsafePaymentServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedPaymentServiceServer provides a mock function with no fields
func (_m *UnsafePaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {
	_m.Called()
}

// NewUnsafePaymentServiceServer creates a new instance of UnsafePaymentServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafePaymentServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafePaymentServiceServer {
	mock := &UnsafePaymentServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
