services:
  envoy:
    image: envoyproxy/envoy:v1.34.1
    container_name: envoy_gateway
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "info"]
    volumes:
      - ../../envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "8088:8088"
      - "9901:9901"
    restart: unless-stopped
    networks:
      - microservices-net

networks:
  microservices-net:
    external: true
