// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: order/v1/order.proto

package order_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaymentMethod описывает доступные способы оплаты в системе.
type PaymentMethod int32

const (
	// UNKNOWN - способ оплаты не указан или неизвестен (значение по умолчанию).
	PaymentMethod_PAYMENT_METHOD_UNKNOWN PaymentMethod = 0
	// CARD - оплата банковской картой.
	PaymentMethod_PAYMENT_METHOD_CARD PaymentMethod = 1
	// SBP - оплата через Систему быстрых платежей.
	PaymentMethod_PAYMENT_METHOD_SBP PaymentMethod = 2
	// CREDIT_CARD - оплата кредитной картой.
	PaymentMethod_PAYMENT_METHOD_CREDIT_CARD PaymentMethod = 3
	// INVESTOR_MONEY - оплата средствами инвестора.
	PaymentMethod_PAYMENT_METHOD_INVESTOR_MONEY PaymentMethod = 4
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNKNOWN",
		1: "PAYMENT_METHOD_CARD",
		2: "PAYMENT_METHOD_SBP",
		3: "PAYMENT_METHOD_CREDIT_CARD",
		4: "PAYMENT_METHOD_INVESTOR_MONEY",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNKNOWN":        0,
		"PAYMENT_METHOD_CARD":           1,
		"PAYMENT_METHOD_SBP":            2,
		"PAYMENT_METHOD_CREDIT_CARD":    3,
		"PAYMENT_METHOD_INVESTOR_MONEY": 4,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_order_v1_order_proto_enumTypes[0].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_order_v1_order_proto_enumTypes[0]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{0}
}

// CancelOrderRequest содержит параметры для отмены заказа.
type CancelOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// order_uuid - уникальный идентификатор отменяемого заказа.
	OrderUuid     string `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *CancelOrderRequest) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

// CancelOrderResponse возвращает пустой ответ при успешной отмене (204 No Content).
type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{1}
}

// GetOrderByUUIDRequest содержит параметры для запроса информации о заказе.
type GetOrderByUUIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// order_uuid - уникальный идентификатор искомого заказа.
	OrderUuid     string `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByUUIDRequest) Reset() {
	*x = GetOrderByUUIDRequest{}
	mi := &file_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByUUIDRequest) ProtoMessage() {}

func (x *GetOrderByUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByUUIDRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByUUIDRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderByUUIDRequest) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

// GetOrderByUUIDResponse содержит полную информацию о заказе.
type GetOrderByUUIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByUUIDResponse) Reset() {
	*x = GetOrderByUUIDResponse{}
	mi := &file_order_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByUUIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByUUIDResponse) ProtoMessage() {}

func (x *GetOrderByUUIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByUUIDResponse.ProtoReflect.Descriptor instead.
func (*GetOrderByUUIDResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderByUUIDResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// Order - заказ, который создает пользователь
type Order struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// order_uuid - уникальный идентификатор заказа.
	OrderUuid string `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	// user_uuid - идентификатор пользователя, создавшего заказ.
	UserUuid string `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	// part_uuids - список идентификаторов заказанных деталей/товаров.
	PartUuids []string `protobuf:"bytes,3,rep,name=part_uuids,json=partUuids,proto3" json:"part_uuids,omitempty"`
	// total_price - общая стоимость заказа.
	TotalPrice float64 `protobuf:"fixed64,4,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	// transaction_uuid - идентификатор транзакции оплаты (если есть).
	TransactionUuid string `protobuf:"bytes,5,opt,name=transaction_uuid,json=transactionUuid,proto3" json:"transaction_uuid,omitempty"`
	// payment_method - выбранный способ оплаты.
	PaymentMethod PaymentMethod `protobuf:"varint,6,opt,name=payment_method,json=paymentMethod,proto3,enum=order.v1.PaymentMethod" json:"payment_method,omitempty"`
	// status - текущий статус заказа.
	Status        string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *Order) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *Order) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *Order) GetPartUuids() []string {
	if x != nil {
		return x.PartUuids
	}
	return nil
}

func (x *Order) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Order) GetTransactionUuid() string {
	if x != nil {
		return x.TransactionUuid
	}
	return ""
}

func (x *Order) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNKNOWN
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// CreateOrderRequest содержит данные, необходимые для создания нового заказа.
type CreateOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_uuid - идентификатор пользователя-покупателя.
	UserUuid string `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	// part_uuids - список идентификаторов товаров для заказа.
	PartUuids     []string `protobuf:"bytes,2,rep,name=part_uuids,json=partUuids,proto3" json:"part_uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrderRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *CreateOrderRequest) GetPartUuids() []string {
	if x != nil {
		return x.PartUuids
	}
	return nil
}

// CreateOrderResponse возвращает базовую информацию о только что созданном заказе.
type CreateOrderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// order_uuid - присвоенный уникальный идентификатор нового заказа.
	OrderUuid string `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	// total_price - рассчитанная итоговая стоимость.
	TotalPrice    float64 `protobuf:"fixed64,2,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *CreateOrderResponse) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *CreateOrderResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

// PayOrderRequest содержит параметры для старта оплаты.
type PayOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// order_uuid - идентификатор оплачиваемого заказа.
	OrderUuid string `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	// payment_method - способ, которым клиент хочет оплатить заказ.
	PaymentMethod PaymentMethod `protobuf:"varint,2,opt,name=payment_method,json=paymentMethod,proto3,enum=order.v1.PaymentMethod" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderRequest) Reset() {
	*x = PayOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderRequest) ProtoMessage() {}

func (x *PayOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderRequest.ProtoReflect.Descriptor instead.
func (*PayOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *PayOrderRequest) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *PayOrderRequest) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNKNOWN
}

// PayOrderResponse возвращает информацию о транзакции.
type PayOrderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// transaction_uuid - идентификатор созданной платежной транзакции.
	TransactionUuid string `protobuf:"bytes,1,opt,name=transaction_uuid,json=transactionUuid,proto3" json:"transaction_uuid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PayOrderResponse) Reset() {
	*x = PayOrderResponse{}
	mi := &file_order_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderResponse) ProtoMessage() {}

func (x *PayOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderResponse.ProtoReflect.Descriptor instead.
func (*PayOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{8}
}

func (x *PayOrderResponse) GetTransactionUuid() string {
	if x != nil {
		return x.TransactionUuid
	}
	return ""
}

var File_order_v1_order_proto protoreflect.FileDescriptor

const file_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x14order/v1/order.proto\x12\border.v1\x1a\x1cgoogle/api/annotations.proto\"3\n" +
	"\x12CancelOrderRequest\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\torderUuid\"\x15\n" +
	"\x13CancelOrderResponse\"6\n" +
	"\x15GetOrderByUUIDRequest\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\torderUuid\"?\n" +
	"\x16GetOrderByUUIDResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderR\x05order\"\x86\x02\n" +
	"\x05Order\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\torderUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12\x1d\n" +
	"\n" +
	"part_uuids\x18\x03 \x03(\tR\tpartUuids\x12\x1f\n" +
	"\vtotal_price\x18\x04 \x01(\x01R\n" +
	"totalPrice\x12)\n" +
	"\x10transaction_uuid\x18\x05 \x01(\tR\x0ftransactionUuid\x12>\n" +
	"\x0epayment_method\x18\x06 \x01(\x0e2\x17.order.v1.PaymentMethodR\rpaymentMethod\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"P\n" +
	"\x12CreateOrderRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x1d\n" +
	"\n" +
	"part_uuids\x18\x02 \x03(\tR\tpartUuids\"U\n" +
	"\x13CreateOrderResponse\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\torderUuid\x12\x1f\n" +
	"\vtotal_price\x18\x02 \x01(\x01R\n" +
	"totalPrice\"p\n" +
	"\x0fPayOrderRequest\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\torderUuid\x12>\n" +
	"\x0epayment_method\x18\x02 \x01(\x0e2\x17.order.v1.PaymentMethodR\rpaymentMethod\"=\n" +
	"\x10PayOrderResponse\x12)\n" +
	"\x10transaction_uuid\x18\x01 \x01(\tR\x0ftransactionUuid*\x9f\x01\n" +
	"\rPaymentMethod\x12\x1a\n" +
	"\x16PAYMENT_METHOD_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13PAYMENT_METHOD_CARD\x10\x01\x12\x16\n" +
	"\x12PAYMENT_METHOD_SBP\x10\x02\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_CREDIT_CARD\x10\x03\x12!\n" +
	"\x1dPAYMENT_METHOD_INVESTOR_MONEY\x10\x042\xd6\x03\n" +
	"\fOrderService\x12e\n" +
	"\vCreateOrder\x12\x1c.order.v1.CreateOrderRequest\x1a\x1d.order.v1.CreateOrderResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/orders\x12m\n" +
	"\bPayOrder\x12\x19.order.v1.PayOrderRequest\x1a\x1a.order.v1.PayOrderResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/orders/{order_uuid}/pay\x12x\n" +
	"\x0eGetOrderByUUID\x12\x1f.order.v1.GetOrderByUUIDRequest\x1a .order.v1.GetOrderByUUIDResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/orders/{order_uuid}\x12v\n" +
	"\vCancelOrder\x12\x1c.order.v1.CancelOrderRequest\x1a\x1d.order.v1.CancelOrderResponse\"*\x82\xd3\xe4\x93\x02$\"\"/api/v1/orders/{order_uuid}/cancelB$Z\"OrderService/pkg/order/v1;order_v1b\x06proto3"

var (
	file_order_v1_order_proto_rawDescOnce sync.Once
	file_order_v1_order_proto_rawDescData []byte
)

func file_order_v1_order_proto_rawDescGZIP() []byte {
	file_order_v1_order_proto_rawDescOnce.Do(func() {
		file_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)))
	})
	return file_order_v1_order_proto_rawDescData
}

var file_order_v1_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_order_v1_order_proto_goTypes = []any{
	(PaymentMethod)(0),             // 0: order.v1.PaymentMethod
	(*CancelOrderRequest)(nil),     // 1: order.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),    // 2: order.v1.CancelOrderResponse
	(*GetOrderByUUIDRequest)(nil),  // 3: order.v1.GetOrderByUUIDRequest
	(*GetOrderByUUIDResponse)(nil), // 4: order.v1.GetOrderByUUIDResponse
	(*Order)(nil),                  // 5: order.v1.Order
	(*CreateOrderRequest)(nil),     // 6: order.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),    // 7: order.v1.CreateOrderResponse
	(*PayOrderRequest)(nil),        // 8: order.v1.PayOrderRequest
	(*PayOrderResponse)(nil),       // 9: order.v1.PayOrderResponse
}
var file_order_v1_order_proto_depIdxs = []int32{
	5, // 0: order.v1.GetOrderByUUIDResponse.order:type_name -> order.v1.Order
	0, // 1: order.v1.Order.payment_method:type_name -> order.v1.PaymentMethod
	0, // 2: order.v1.PayOrderRequest.payment_method:type_name -> order.v1.PaymentMethod
	6, // 3: order.v1.OrderService.CreateOrder:input_type -> order.v1.CreateOrderRequest
	8, // 4: order.v1.OrderService.PayOrder:input_type -> order.v1.PayOrderRequest
	3, // 5: order.v1.OrderService.GetOrderByUUID:input_type -> order.v1.GetOrderByUUIDRequest
	1, // 6: order.v1.OrderService.CancelOrder:input_type -> order.v1.CancelOrderRequest
	7, // 7: order.v1.OrderService.CreateOrder:output_type -> order.v1.CreateOrderResponse
	9, // 8: order.v1.OrderService.PayOrder:output_type -> order.v1.PayOrderResponse
	4, // 9: order.v1.OrderService.GetOrderByUUID:output_type -> order.v1.GetOrderByUUIDResponse
	2, // 10: order.v1.OrderService.CancelOrder:output_type -> order.v1.CancelOrderResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_order_v1_order_proto_init() }
func file_order_v1_order_proto_init() {
	if File_order_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v1_order_proto_goTypes,
		DependencyIndexes: file_order_v1_order_proto_depIdxs,
		EnumInfos:         file_order_v1_order_proto_enumTypes,
		MessageInfos:      file_order_v1_order_proto_msgTypes,
	}.Build()
	File_order_v1_order_proto = out.File
	file_order_v1_order_proto_goTypes = nil
	file_order_v1_order_proto_depIdxs = nil
}
