// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	inventory_v1 "github.com/jefrryss/go-grpc-microservices/shared/pkg/proto/inventory/v1"
	mock "github.com/stretchr/testify/mock"
)

// InventoryServiceServer is an autogenerated mock type for the InventoryServiceServer type
type InventoryServiceServer struct {
	mock.Mock
}

// GetPart provides a mock function with given fields: _a0, _a1
func (_m *InventoryServiceServer) GetPart(_a0 context.Context, _a1 *inventory_v1.GetPartRequest) (*inventory_v1.GetPartResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *inventory_v1.GetPartResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *inventory_v1.GetPartRequest) (*inventory_v1.GetPartResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *inventory_v1.GetPartRequest) *inventory_v1.GetPartResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventory_v1.GetPartResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *inventory_v1.GetPartRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListParts provides a mock function with given fields: _a0, _a1
func (_m *InventoryServiceServer) ListParts(_a0 context.Context, _a1 *inventory_v1.ListPartsRequest) (*inventory_v1.ListPartsResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 *inventory_v1.ListPartsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *inventory_v1.ListPartsRequest) (*inventory_v1.ListPartsResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *inventory_v1.ListPartsRequest) *inventory_v1.ListPartsResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventory_v1.ListPartsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *inventory_v1.ListPartsRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedInventoryServiceServer provides a mock function with no fields
func (_m *InventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {
	_m.Called()
}

// NewInventoryServiceServer creates a new instance of InventoryServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryServiceServer {
	mock := &InventoryServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
