// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	inventory_v1 "github.com/jefrryss/go-grpc-microservices/shared/pkg/proto/inventory/v1"
	mock "github.com/stretchr/testify/mock"
)

// InventoryServiceClient is an autogenerated mock type for the InventoryServiceClient type
type InventoryServiceClient struct {
	mock.Mock
}

// GetPart provides a mock function with given fields: ctx, in, opts
func (_m *InventoryServiceClient) GetPart(ctx context.Context, in *inventory_v1.GetPartRequest, opts ...grpc.CallOption) (*inventory_v1.GetPartResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *inventory_v1.GetPartResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *inventory_v1.GetPartRequest, ...grpc.CallOption) (*inventory_v1.GetPartResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *inventory_v1.GetPartRequest, ...grpc.CallOption) *inventory_v1.GetPartResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventory_v1.GetPartResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *inventory_v1.GetPartRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListParts provides a mock function with given fields: ctx, in, opts
func (_m *InventoryServiceClient) ListParts(ctx context.Context, in *inventory_v1.ListPartsRequest, opts ...grpc.CallOption) (*inventory_v1.ListPartsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 *inventory_v1.ListPartsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *inventory_v1.ListPartsRequest, ...grpc.CallOption) (*inventory_v1.ListPartsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *inventory_v1.ListPartsRequest, ...grpc.CallOption) *inventory_v1.ListPartsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventory_v1.ListPartsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *inventory_v1.ListPartsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInventoryServiceClient creates a new instance of InventoryServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryServiceClient {
	mock := &InventoryServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
