// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isValue_Kind is an autogenerated mock type for the isValue_Kind type
type isValue_Kind struct {
	mock.Mock
}

// isValue_Kind provides a mock function with no fields
func (_m *isValue_Kind) isValue_Kind() {
	_m.Called()
}

// newIsValue_Kind creates a new instance of isValue_Kind. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIsValue_Kind(t interface {
	mock.TestingT
	Cleanup(func())
}) *isValue_Kind {
	mock := &isValue_Kind{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
