// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeInventoryServiceServer is an autogenerated mock type for the UnsafeInventoryServiceServer type
type UnsafeInventoryServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedInventoryServiceServer provides a mock function with no fields
func (_m *UnsafeInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {
	_m.Called()
}

// NewUnsafeInventoryServiceServer creates a new instance of UnsafeInventoryServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeInventoryServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeInventoryServiceServer {
	mock := &UnsafeInventoryServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
