// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/jefrryss/go-grpc-microservices/OrderService/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function with given fields: ctx, orderUUID
func (_m *Repository) GetOrder(ctx context.Context, orderUUID uuid.UUID) (*model.Order, error) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Order, error)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Order); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type Repository_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
func (_e *Repository_Expecter) GetOrder(ctx interface{}, orderUUID interface{}) *Repository_GetOrder_Call {
	return &Repository_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderUUID)}
}

func (_c *Repository_GetOrder_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID)) *Repository_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_GetOrder_Call) Return(_a0 *model.Order, _a1 error) *Repository_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Order, error)) *Repository_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// SetOrder provides a mock function with given fields: ctx, order
func (_m *Repository) SetOrder(ctx context.Context, order *model.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for SetOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_SetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOrder'
type Repository_SetOrder_Call struct {
	*mock.Call
}

// SetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *Repository_Expecter) SetOrder(ctx interface{}, order interface{}) *Repository_SetOrder_Call {
	return &Repository_SetOrder_Call{Call: _e.mock.On("SetOrder", ctx, order)}
}

func (_c *Repository_SetOrder_Call) Run(run func(ctx context.Context, order *model.Order)) *Repository_SetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Order))
	})
	return _c
}

func (_c *Repository_SetOrder_Call) Return(_a0 error) *Repository_SetOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_SetOrder_Call) RunAndReturn(run func(context.Context, *model.Order) error) *Repository_SetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
