with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: false

packages:
  .:
    config:
      recursive: true
      include-regex: ".*(Service|Repository|Client)$"