// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/jefrryss/go-grpc-microservices/OrderService/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, orderUUID
func (_m *Service) CancelOrder(ctx context.Context, orderUUID uuid.UUID) error {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type Service_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
func (_e *Service_Expecter) CancelOrder(ctx interface{}, orderUUID interface{}) *Service_CancelOrder_Call {
	return &Service_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, orderUUID)}
}

func (_c *Service_CancelOrder_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID)) *Service_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Service_CancelOrder_Call) Return(_a0 error) *Service_CancelOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_CancelOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *Service_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, userUUID, partsUUIDS
func (_m *Service) CreateOrder(ctx context.Context, userUUID uuid.UUID, partsUUIDS []uuid.UUID) (uuid.UUID, float64, error) {
	ret := _m.Called(ctx, userUUID, partsUUIDS)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 uuid.UUID
	var r1 float64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID) (uuid.UUID, float64, error)); ok {
		return rf(ctx, userUUID, partsUUIDS)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID) uuid.UUID); ok {
		r0 = rf(ctx, userUUID, partsUUIDS)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, []uuid.UUID) float64); ok {
		r1 = rf(ctx, userUUID, partsUUIDS)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, []uuid.UUID) error); ok {
		r2 = rf(ctx, userUUID, partsUUIDS)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Service_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type Service_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
//   - partsUUIDS []uuid.UUID
func (_e *Service_Expecter) CreateOrder(ctx interface{}, userUUID interface{}, partsUUIDS interface{}) *Service_CreateOrder_Call {
	return &Service_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, userUUID, partsUUIDS)}
}

func (_c *Service_CreateOrder_Call) Run(run func(ctx context.Context, userUUID uuid.UUID, partsUUIDS []uuid.UUID)) *Service_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]uuid.UUID))
	})
	return _c
}

func (_c *Service_CreateOrder_Call) Return(_a0 uuid.UUID, _a1 float64, _a2 error) *Service_CreateOrder_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Service_CreateOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID, []uuid.UUID) (uuid.UUID, float64, error)) *Service_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, orderUUID
func (_m *Service) GetOrder(ctx context.Context, orderUUID uuid.UUID) (*model.Order, error) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Order, error)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Order); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type Service_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
func (_e *Service_Expecter) GetOrder(ctx interface{}, orderUUID interface{}) *Service_GetOrder_Call {
	return &Service_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderUUID)}
}

func (_c *Service_GetOrder_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID)) *Service_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Service_GetOrder_Call) Return(_a0 *model.Order, _a1 error) *Service_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Order, error)) *Service_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function with given fields: ctx, orderUUID, paymentMethod
func (_m *Service) PayOrder(ctx context.Context, orderUUID uuid.UUID, paymentMethod model.PaymentMethod) (uuid.UUID, error) {
	ret := _m.Called(ctx, orderUUID, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.PaymentMethod) (uuid.UUID, error)); ok {
		return rf(ctx, orderUUID, paymentMethod)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.PaymentMethod) uuid.UUID); ok {
		r0 = rf(ctx, orderUUID, paymentMethod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.PaymentMethod) error); ok {
		r1 = rf(ctx, orderUUID, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type Service_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
//   - paymentMethod model.PaymentMethod
func (_e *Service_Expecter) PayOrder(ctx interface{}, orderUUID interface{}, paymentMethod interface{}) *Service_PayOrder_Call {
	return &Service_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, orderUUID, paymentMethod)}
}

func (_c *Service_PayOrder_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID, paymentMethod model.PaymentMethod)) *Service_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.PaymentMethod))
	})
	return _c
}

func (_c *Service_PayOrder_Call) Return(_a0 uuid.UUID, _a1 error) *Service_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_PayOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.PaymentMethod) (uuid.UUID, error)) *Service_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
