// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/jefrryss/go-grpc-microservices/OrderService/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// InventoryClient is an autogenerated mock type for the InventoryClient type
type InventoryClient struct {
	mock.Mock
}

type InventoryClient_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryClient) EXPECT() *InventoryClient_Expecter {
	return &InventoryClient_Expecter{mock: &_m.Mock}
}

// GetListParts provides a mock function with given fields: ctx, parts
func (_m *InventoryClient) GetListParts(ctx context.Context, parts []uuid.UUID) ([]*model.Part, error) {
	ret := _m.Called(ctx, parts)

	if len(ret) == 0 {
		panic("no return value specified for GetListParts")
	}

	var r0 []*model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]*model.Part, error)); ok {
		return rf(ctx, parts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []*model.Part); ok {
		r0 = rf(ctx, parts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, parts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryClient_GetListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetListParts'
type InventoryClient_GetListParts_Call struct {
	*mock.Call
}

// GetListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - parts []uuid.UUID
func (_e *InventoryClient_Expecter) GetListParts(ctx interface{}, parts interface{}) *InventoryClient_GetListParts_Call {
	return &InventoryClient_GetListParts_Call{Call: _e.mock.On("GetListParts", ctx, parts)}
}

func (_c *InventoryClient_GetListParts_Call) Run(run func(ctx context.Context, parts []uuid.UUID)) *InventoryClient_GetListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *InventoryClient_GetListParts_Call) Return(_a0 []*model.Part, _a1 error) *InventoryClient_GetListParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryClient_GetListParts_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]*model.Part, error)) *InventoryClient_GetListParts_Call {
	_c.Call.Return(run)
	return _c
}

// GetPart provides a mock function with given fields: ctx, uuidPart
func (_m *InventoryClient) GetPart(ctx context.Context, uuidPart uuid.UUID) (*model.Part, error) {
	ret := _m.Called(ctx, uuidPart)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Part, error)); ok {
		return rf(ctx, uuidPart)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Part); ok {
		r0 = rf(ctx, uuidPart)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, uuidPart)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryClient_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type InventoryClient_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - uuidPart uuid.UUID
func (_e *InventoryClient_Expecter) GetPart(ctx interface{}, uuidPart interface{}) *InventoryClient_GetPart_Call {
	return &InventoryClient_GetPart_Call{Call: _e.mock.On("GetPart", ctx, uuidPart)}
}

func (_c *InventoryClient_GetPart_Call) Run(run func(ctx context.Context, uuidPart uuid.UUID)) *InventoryClient_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *InventoryClient_GetPart_Call) Return(_a0 *model.Part, _a1 error) *InventoryClient_GetPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryClient_GetPart_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Part, error)) *InventoryClient_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryClient creates a new instance of InventoryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryClient {
	mock := &InventoryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
