// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/jefrryss/go-grpc-microservices/PaymentService/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CreateTransaction provides a mock function with given fields: ctx, orderUUID, userrUUID, paymentMethod
func (_m *Service) CreateTransaction(ctx context.Context, orderUUID uuid.UUID, userrUUID uuid.UUID, paymentMethod model.PaymentMethod) (uuid.UUID, error) {
	ret := _m.Called(ctx, orderUUID, userrUUID, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.PaymentMethod) (uuid.UUID, error)); ok {
		return rf(ctx, orderUUID, userrUUID, paymentMethod)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.PaymentMethod) uuid.UUID); ok {
		r0 = rf(ctx, orderUUID, userrUUID, paymentMethod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, model.PaymentMethod) error); ok {
		r1 = rf(ctx, orderUUID, userrUUID, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_CreateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransaction'
type Service_CreateTransaction_Call struct {
	*mock.Call
}

// CreateTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
//   - userrUUID uuid.UUID
//   - paymentMethod model.PaymentMethod
func (_e *Service_Expecter) CreateTransaction(ctx interface{}, orderUUID interface{}, userrUUID interface{}, paymentMethod interface{}) *Service_CreateTransaction_Call {
	return &Service_CreateTransaction_Call{Call: _e.mock.On("CreateTransaction", ctx, orderUUID, userrUUID, paymentMethod)}
}

func (_c *Service_CreateTransaction_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID, userrUUID uuid.UUID, paymentMethod model.PaymentMethod)) *Service_CreateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(model.PaymentMethod))
	})
	return _c
}

func (_c *Service_CreateTransaction_Call) Return(_a0 uuid.UUID, _a1 error) *Service_CreateTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_CreateTransaction_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, model.PaymentMethod) (uuid.UUID, error)) *Service_CreateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
