services:
  order-service:
    build:
      context: ../../..
      dockerfile: OrderService/Dockerfile
    image: order-service:latest
    container_name: order_service

    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_NAME}?sslmode=disable"
      INVENTORY_SERVICE_ADDRESS: inventory-service:50052
      PAYMENT_SERVICE_ADDRESS: payment-service:50053

    ports:
      - "50051:50051"
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy
      order-migrator:
        condition: service_completed_successfully

    restart: unless-stopped

    networks:
      - microservices-net

  order-migrator:
    image: order-service:latest
    container_name: order_migrator
    entrypoint: ["./migrator"]

    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_NAME}?sslmode=disable"
      MIGRATIONS_PATH: migrations

    depends_on:
      postgres:
        condition: service_healthy

    restart: "no"

    networks:
      - microservices-net

  postgres:
    image: postgres:17.0-alpine3.20
    container_name: order_postgres

    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_order_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U "$${POSTGRES_USER}" -d "$${POSTGRES_DB}"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: unless-stopped

    networks:
      - microservices-net

volumes:
  postgres_order_data:

networks:
  microservices-net:
    external: true
