// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	order_v1 "github.com/jefrryss/go-grpc-microservices/shared/pkg/proto/order/v1"
	mock "github.com/stretchr/testify/mock"
)

// OrderServiceServer is an autogenerated mock type for the OrderServiceServer type
type OrderServiceServer struct {
	mock.Mock
}

// CancelOrder provides a mock function with given fields: _a0, _a1
func (_m *OrderServiceServer) CancelOrder(_a0 context.Context, _a1 *order_v1.CancelOrderRequest) (*order_v1.CancelOrderResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 *order_v1.CancelOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.CancelOrderRequest) (*order_v1.CancelOrderResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.CancelOrderRequest) *order_v1.CancelOrderResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_v1.CancelOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *order_v1.CancelOrderRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateOrder provides a mock function with given fields: _a0, _a1
func (_m *OrderServiceServer) CreateOrder(_a0 context.Context, _a1 *order_v1.CreateOrderRequest) (*order_v1.CreateOrderResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *order_v1.CreateOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.CreateOrderRequest) (*order_v1.CreateOrderResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.CreateOrderRequest) *order_v1.CreateOrderResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_v1.CreateOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *order_v1.CreateOrderRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderByUUID provides a mock function with given fields: _a0, _a1
func (_m *OrderServiceServer) GetOrderByUUID(_a0 context.Context, _a1 *order_v1.GetOrderByUUIDRequest) (*order_v1.GetOrderByUUIDResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByUUID")
	}

	var r0 *order_v1.GetOrderByUUIDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.GetOrderByUUIDRequest) (*order_v1.GetOrderByUUIDResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.GetOrderByUUIDRequest) *order_v1.GetOrderByUUIDResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_v1.GetOrderByUUIDResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *order_v1.GetOrderByUUIDRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayOrder provides a mock function with given fields: _a0, _a1
func (_m *OrderServiceServer) PayOrder(_a0 context.Context, _a1 *order_v1.PayOrderRequest) (*order_v1.PayOrderResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *order_v1.PayOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.PayOrderRequest) (*order_v1.PayOrderResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.PayOrderRequest) *order_v1.PayOrderResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_v1.PayOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *order_v1.PayOrderRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedOrderServiceServer provides a mock function with no fields
func (_m *OrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {
	_m.Called()
}

// NewOrderServiceServer creates a new instance of OrderServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderServiceServer {
	mock := &OrderServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
