// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	order_v1 "github.com/jefrryss/go-grpc-microservices/shared/pkg/proto/order/v1"
)

// OrderServiceClient is an autogenerated mock type for the OrderServiceClient type
type OrderServiceClient struct {
	mock.Mock
}

// CancelOrder provides a mock function with given fields: ctx, in, opts
func (_m *OrderServiceClient) CancelOrder(ctx context.Context, in *order_v1.CancelOrderRequest, opts ...grpc.CallOption) (*order_v1.CancelOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 *order_v1.CancelOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.CancelOrderRequest, ...grpc.CallOption) (*order_v1.CancelOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.CancelOrderRequest, ...grpc.CallOption) *order_v1.CancelOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_v1.CancelOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *order_v1.CancelOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateOrder provides a mock function with given fields: ctx, in, opts
func (_m *OrderServiceClient) CreateOrder(ctx context.Context, in *order_v1.CreateOrderRequest, opts ...grpc.CallOption) (*order_v1.CreateOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *order_v1.CreateOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.CreateOrderRequest, ...grpc.CallOption) (*order_v1.CreateOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.CreateOrderRequest, ...grpc.CallOption) *order_v1.CreateOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_v1.CreateOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *order_v1.CreateOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderByUUID provides a mock function with given fields: ctx, in, opts
func (_m *OrderServiceClient) GetOrderByUUID(ctx context.Context, in *order_v1.GetOrderByUUIDRequest, opts ...grpc.CallOption) (*order_v1.GetOrderByUUIDResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByUUID")
	}

	var r0 *order_v1.GetOrderByUUIDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.GetOrderByUUIDRequest, ...grpc.CallOption) (*order_v1.GetOrderByUUIDResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.GetOrderByUUIDRequest, ...grpc.CallOption) *order_v1.GetOrderByUUIDResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_v1.GetOrderByUUIDResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *order_v1.GetOrderByUUIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayOrder provides a mock function with given fields: ctx, in, opts
func (_m *OrderServiceClient) PayOrder(ctx context.Context, in *order_v1.PayOrderRequest, opts ...grpc.CallOption) (*order_v1.PayOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *order_v1.PayOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.PayOrderRequest, ...grpc.CallOption) (*order_v1.PayOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.PayOrderRequest, ...grpc.CallOption) *order_v1.PayOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order_v1.PayOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *order_v1.PayOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderServiceClient creates a new instance of OrderServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderServiceClient {
	mock := &OrderServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
