services:
  payment-service:
    build:
      context: ../../..
      dockerfile: PaymentService/Dockerfile

    image: payment-service:latest
    container_name: payment_service

    environment:
      GRPC_HOST: 0.0.0.0
      GRPC_PORT: ${GRPC_PORT:-50053}
      LOGGER_LEVEL: ${LOGGER_LEVEL:-info}
      LOGGER_AS_JSON: ${LOGGER_AS_JSON:-true}
      OTEL_EXPORTER_OTLP_ENDPOINT: jaeger:4317

    ports:
      - "50053:50053"

    restart: unless-stopped

    networks:
      - microservices-net

networks:
  microservices-net:
    external: true
